// Code generated by hand. DO NOT EDIT.
package infracode

import (
	"github.com/devilmonastery/infracode/domains/cicd/drone"
	"github.com/devilmonastery/infracode/domains/makefile"
	"github.com/devilmonastery/infracode/domains/renovate"
	"github.com/devilmonastery/infracode/infragen"
)

const (
	dockerRegistry = "registry.local.rothwell.us/devilmonastery"
	workerImage    = "renovate-worker"
)

// Generate registers the domains that render this repository's generated
// files.
func Generate(gen *infragen.Generator) {
	makefile.New(gen)
	drone.New(gen,
		drone.WithGoVersion("1.26.4"),
		drone.WithGoModuleAuth("github.com/devilmonastery/*", "github.com/devilmonastery/*", "github_module_token"),
		drone.WithBuildKitBuild(dockerRegistry, workerImage),
		drone.WithBuildKitHost("tcp://buildkitd.homes.svc.cluster.local:1234"),
	)
	renovate.New(gen,
		renovate.WithFileMatches("**/Dockerfile", "deploy/**"),
	)
}
